# Generated by Django 5.0.3 on 2024-03-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=120, null=True)),
                ('product_description', models.CharField(blank=True, max_length=120, null=True)),
                ('product_sku', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
