# Generated by Django 5.0.3 on 2024-03-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraperAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_products',
            old_name='product_description',
            new_name='product_link',
        ),
    ]
