# Generated by Django 5.0.3 on 2024-03-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperAPI', '0002_rename_product_description_my_products_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_products',
            name='Product_Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
