# Generated by Django 5.0.3 on 2024-03-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperAPI', '0003_my_products_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_products',
            name='Product_Price',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
