# Generated by Django 5.0.3 on 2024-03-13 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperAPI', '0004_alter_my_products_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_products',
            old_name='Product_Price',
            new_name='product_Price',
        ),
        migrations.AddField(
            model_name='my_products',
            name='highlighted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='my_products',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='app1', to=settings.AUTH_USER_MODEL),
        ),
    ]
